# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fl72_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 483)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 450, 291, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 161))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.cobWGSL72 = QtWidgets.QComboBox(self.groupBox)
        self.cobWGSL72.setGeometry(QtCore.QRect(10, 40, 271, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cobWGSL72.setFont(font)
        self.cobWGSL72.setObjectName("cobWGSL72")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 201, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bWGSL72 = QtWidgets.QPushButton(self.groupBox)
        self.bWGSL72.setGeometry(QtCore.QRect(200, 130, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bWGSL72.setFont(font)
        self.bWGSL72.setObjectName("bWGSL72")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 201, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tbColWGSL72 = QtWidgets.QLineEdit(self.groupBox)
        self.tbColWGSL72.setGeometry(QtCore.QRect(10, 80, 271, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbColWGSL72.setFont(font)
        self.tbColWGSL72.setObjectName("tbColWGSL72")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 191, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(270, 20, 16, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.cbWGSL72 = QtWidgets.QCheckBox(self.groupBox)
        self.cbWGSL72.setGeometry(QtCore.QRect(10, 140, 181, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbWGSL72.setFont(font)
        self.cbWGSL72.setObjectName("cbWGSL72")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 291, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.cobZ = QtWidgets.QComboBox(self.groupBox_2)
        self.cobZ.setGeometry(QtCore.QRect(10, 40, 271, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cobZ.setFont(font)
        self.cobZ.setObjectName("cobZ")
        self.bZ = QtWidgets.QPushButton(self.groupBox_2)
        self.bZ.setGeometry(QtCore.QRect(200, 120, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bZ.setFont(font)
        self.bZ.setObjectName("bZ")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 201, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tbColZ = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbColZ.setGeometry(QtCore.QRect(10, 80, 271, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbColZ.setFont(font)
        self.tbColZ.setObjectName("tbColZ")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 201, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 191, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(270, 20, 16, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 291, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.cobL72 = QtWidgets.QComboBox(self.groupBox_3)
        self.cobL72.setGeometry(QtCore.QRect(10, 40, 271, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cobL72.setFont(font)
        self.cobL72.setObjectName("cobL72")
        self.bL72 = QtWidgets.QPushButton(self.groupBox_3)
        self.bL72.setGeometry(QtCore.QRect(200, 70, 81, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bL72.setFont(font)
        self.bL72.setObjectName("bL72")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 201, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(270, 20, 16, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cbL72 = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbL72.setGeometry(QtCore.QRect(10, 80, 181, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbL72.setFont(font)
        self.cbL72.setObjectName("cbL72")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Correction tool for Lambert 72"))
        self.groupBox.setTitle(_translate("Dialog", "Convert && fix (x,y,z) WGS84 -> Lambert 72"))
        self.label.setText(_translate("Dialog", "Layer to convert :"))
        self.bWGSL72.setText(_translate("Dialog", "Convert"))
        self.label_3.setText(_translate("Dialog", "Field containing Z value :"))
        self.tbColWGSL72.setText(_translate("Dialog", "projected"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>The new Z value will be added to HDNG column</p></body></html>"))
        self.label_10.setToolTip(_translate("Dialog", "<html><head/><body><p>Create a new - converted and fixed - layer in Lambert72 and add a \'HDNG\' column that contains the new height value.</p><p>Z field value can be:</p><p>- &quot;z&quot;</p><p>- &quot;x y z&quot; (space separator)</p></body></html>"))
        self.label_10.setText(_translate("Dialog", "?"))
        self.cbWGSL72.setText(_translate("Dialog", "Save SHP (suffix \'_fix\')"))
        self.groupBox_2.setTitle(_translate("Dialog", "Fix (z) WGS84"))
        self.bZ.setText(_translate("Dialog", "Convert"))
        self.label_2.setText(_translate("Dialog", "Layer to fix :"))
        self.tbColZ.setText(_translate("Dialog", "projected"))
        self.label_5.setText(_translate("Dialog", "Field containing Z value :"))
        self.label_7.setText(_translate("Dialog", "The new Z value will be added to a HDNG column"))
        self.label_8.setToolTip(_translate("Dialog", "<html><head/><body><p>Modify the WGS84 layer by adding a \'HDNG\' column that contains the new height value.</p><p>Z field value can be:</p><p>- &quot;z&quot;</p><p>- &quot;x y z&quot; (space separator)</p></body></html>"))
        self.label_8.setText(_translate("Dialog", "?"))
        self.groupBox_3.setTitle(_translate("Dialog", "Fix (x,y) Lambert72"))
        self.bL72.setText(_translate("Dialog", "Convert"))
        self.label_4.setText(_translate("Dialog", "Layer to fix :"))
        self.label_9.setToolTip(_translate("Dialog", "<html><head/><body><p>Create a new Lambert 72 layer by fixing (x,y) coordinates.</p></body></html>"))
        self.label_9.setText(_translate("Dialog", "?"))
        self.cbL72.setText(_translate("Dialog", "Save SHP (suffix \'_fix\')"))

